### ISSUE TITLE
Command not found: poe

### ISSUE THREAD

**Issue by LAKHANVEER** [OpenNyAI/jugalbandi#1]
Hello everyone,
After latest changes in the repository code by the team while using jb-generic-folder, after successful installation of poetry along with all its dependencies and activating virtual environment when I am trying to run the command:- poetry run poe start, I am getting an error:- Command not found: poe
Is anyone facing the same issue?  
If anyone can provide me the suggestions to fix the issue it would be a great help.
Thank you

**Comment by KaranrajM** [comment]
Hi @LAKHANVEER it seems the poe command is not found when trying poetry command.
You can try these following steps to debug the app:

1. To ensure that Poetry is correctly installed, try running poetry --version in your command prompt
2. Also verify whether path has been configuration: 
    The poetry path may be found in the below path: C:\User\<YourUserName>\AppData\Roaming\pypoetry\venv\Script
     If it is not found in the above path, please find out your respective poetry downloaded path and add it to the system path.
3. Try the poetry --version command again for proper installation

Hope this solution helps!
